sm8450-common: Use QTI health service
Switch the health service from Xiaomi to QTI.

error: build/soong/fsgen/Android.bp:41:1: dependency
android.hardware.health-service.qti of
aospa_marble_generated_system_image missing variant:
  os:android,arch:arm64_armv8-2a-dotprod_kryo785
available variants:
  os:android,image:vendor,arch:arm64_armv8-2a-dotprod_kryo785
  os:android,image:recovery,arch:arm64_armv8-2a-dotprod_kryo785

Signed-off-by: ShadeDark6 <nizamfa6@gmail.com>